### PR TITLE
Add method and path based strategy

### PR DESCRIPTION
**Pull request by TheWudu**
Based on the other pull-request i opened a few days ago, we currently use it as this. Defining method and path limits based on a config file. I refactored it a bit to be a bit easier to use, and only pass the options in.

The other PR: https://github.com/dryruby/rack-throttle/pull/36

Also updated the README file.

### CODE REVIEW

**Comment by FreekingDean** [comment]
I don't think this is very intuitive in terms of time based throttling.

```ruby
{
  limits: {
    "methods" => {
      "POST" => 5
    }
  }
}
```

Will that only allow 5 post requests ever?

**Comment by FreekingDean** [comment]
I think this seems more particular to a specific use case. If others chime in here and mention that they would like it we can figure out a way to fix up the configuration.

Otherwise I'm going to suggest we leave it open for a month or so and then re-evaluate.

**Comment by TheWudu** [comment]
I don't think this is a very specific use-case, as the blocking per IP can be done already some steps before the application code.. in nginx, haproxy, ssl endpoint, firwall,.. whatever your setup has.

I think it is common to prevent users to create endless posts, articles, comments, users, whatever (POST requests) depending on your application while don't throttle their GET requests.

I agree that the name could be a bit clearer, so it includes that the value is in "requests per second", as the strategy is derived from `Second`. Or make it configurable from outside (override the time string used in cache key).

What do others think?

**Comment by TheWudu** [comment]
Adapted the code and the Readme. I think it is more clear now and also configurable.

**Comment by FreekingDean** [comment]
Hmm, I was looking through the codebase https://github.com/bensomers/improved-rack-throttle. It seems they took the approach of using matchers in the time window'd requests.

I think that is more intuitive.

I am haveing a hard time giving `TimeWindow` the responsibility of request method/path limiting. I think even sending the request over to the `TimeWindow` classes and sub classes is a bit unnecessary. Could you try implementing something similar to a matcher for a limiter?

IE:
```
def allowed?
  if matcher_exists? && request_matches_method_andor_patch?
    check_time_window_stuffs
  end
end
```

**Comment by TheWudu** [comment]
I had a look at that implementation and it has a critical problem: the performance. If i understand it correctly, then I would have to define a middleware for each rule i want to apply. The rules can be a combination of url / method / user-agent, like that:

```
config.middleware.use Rack::Throttle::Second, max: 10, rules: { method: :get, url: <whatever> }
```

but if i want to apply e.g. 20 (distinct) rules, with distinct max request values. The middleware will be encapsulated 20 times.. 

It may be a bit easier to understand, (not sure about that, as the proposed solution does not seem complex to me) but it is definitely slower and causes (much) more method calls, so less performance. 

And as I am talking about ten-thousands of requests per minute, every millisecond counts.

**Comment by TheWudu** [comment]
We currently use the proposed implementation, having a yml file, loaded on app-start looking like this: 

(test mode limits ;-) )
```
  limits:
    default: 10
    methods:
      POST:  5
      GET:  10
    paths:
      "/users/\\w*/oauth/token": 5
      ...
```

which looks pretty straight forward to me. It may be adapted to configure the interval also, but as that is (now) just an option and we use the default (:seconds), I did not add it to the yml file yet.

**Comment by FreekingDean** [comment]
Hmm I see your point.

I think it could work like this though:


```ruby
config.middleware.use Rack::Throttle::Second, rules: [
  { method: :get, url: '<whatever>', max: 10 },
  { method: :post, url: '<whatever>', max: 5 },
]
```

This is very similar to your approach, but instead I think lends itself more nicely to the current Throttle based on time pattern currently in place.

**Comment by FreekingDean** [comment]
Please don't edit the Version file :)

**Comment by FreekingDean** [comment]
There are still a few open issues on this PR that should be handled before merging. Is this something that you are still looking to merge in?

**Comment by FreekingDean** [comment]
There hasn't been any activity on this in a while I'm going to close this. If this is a feature that someone would like to take over please feel free :)

**Comment by TheWudu** [comment]
Hey, sorry for the late response. Just had not time to deal with it. Currently it works fine for us like this, and if i spend some more effort on that (would like to), I will change and adapt it, and open another PR then. 

Thanks for the patience.

**Pull request closed without merging**
